# Create the service to expose the port
apiVersion: v1
kind: Service
metadata:
  name: mariadb-galera
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 31650
  selector:
    app: mariadb-galera
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-galera
spec:
  serviceName: mariadb-galera
  replicas: 3
  selector:
    matchLabels:
      app: mariadb-galera
  template:
    metadata:
      labels:
        app: mariadb-galera
    spec:
      containers:
      - name: mariadb-galera
        image: mariadb:10.6  # Use a Galera-compatible image
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-galera-secret
              key: mariadb-root-password
        - name: MARIADB_GALERA_CLUSTER
          value: "yes"
        - name: MARIADB_GALERA_ARBITRATOR
          value: "false"
        - name: MARIADB_GALERA_GROUP
          value: "db_group"
        - name: MARIADB_GALERA_OPTIONS
          value: "gcs.fc_limit=256;gmcast.listen_addr=tcp://0.0.0.0:4567"  # Adjust as needed
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mariadb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"  # Replace with your desired StorageClass
      resources:
        requests:
          storage: 3Gi  # Adjust as needed
